### ISSUE TITLE
[BUG] Investigate panic calling getSAN when pawn promoting

### ISSUE THREAD

**Issue by dechristopher** [dechristopher/lio#3]
Stack trace:
```bash
lio-prod_lioctad.1.y2owyavvvr3y@lioctad    | panic: invalid piece
lio-prod_lioctad.1.y2owyavvvr3y@lioctad    |
lio-prod_lioctad.1.y2owyavvvr3y@lioctad    | goroutine 371 [running]:
lio-prod_lioctad.1.y2owyavvvr3y@lioctad    | github.com/dechristopher/octad.(*Board).setBBForPiece(...)
lio-prod_lioctad.1.y2owyavvvr3y@lioctad    | 	github.com/dechristopher/octad@v1.0.3/board.go:440
lio-prod_lioctad.1.y2owyavvvr3y@lioctad    | github.com/dechristopher/octad.(*Board).update(0xc000394340, 0xc0003a79b0)
lio-prod_lioctad.1.y2owyavvvr3y@lioctad    | 	github.com/dechristopher/octad@v1.0.3/board.go:239 +0x955
lio-prod_lioctad.1.y2owyavvvr3y@lioctad    | github.com/dechristopher/octad.(*Position).Update(0xc000314960, 0xc0003a79b0, 0xffffffffffffffff)
lio-prod_lioctad.1.y2owyavvvr3y@lioctad    | 	github.com/dechristopher/octad@v1.0.3/position.go:93 +0x1b6
lio-prod_lioctad.1.y2owyavvvr3y@lioctad    | github.com/dechristopher/octad.getCheckChar(0xc000314960, 0xc0003a79b0, 0x2, 0xe)
lio-prod_lioctad.1.y2owyavvvr3y@lioctad    | 	github.com/dechristopher/octad@v1.0.3/notation.go:197 +0x45
lio-prod_lioctad.1.y2owyavvvr3y@lioctad    | github.com/dechristopher/octad.AlgebraicNotation.Encode(0xc000314960, 0xc0003a79b0, 0x8, 0xc00033a600)
lio-prod_lioctad.1.y2owyavvvr3y@lioctad    | 	github.com/dechristopher/octad@v1.0.3/notation.go:109 +0x50
lio-prod_lioctad.1.y2owyavvvr3y@lioctad    | github.com/dechristopher/lioctad/www/ws/handlers.getSAN(0xc0006e2000, 0xc000293401, 0x18, 0xc00031c470)
lio-prod_lioctad.1.y2owyavvvr3y@lioctad    | 	github.com/dechristopher/lioctad/www/ws/handlers/handle_move.go:140 +0x1d1
lio-prod_lioctad.1.y2owyavvvr3y@lioctad    | github.com/dechristopher/lioctad/www/ws/handlers.current(0xc0006e2000, 0xc0003a7901, 0x0, 0x0, 0xc000c2c000)
lio-prod_lioctad.1.y2owyavvvr3y@lioctad    | 	github.com/dechristopher/lioctad/www/ws/handlers/handle_move.go:90 +0x12a
lio-prod_lioctad.1.y2owyavvvr3y@lioctad    | github.com/dechristopher/lioctad/www/ws/handlers.makeComputerMove(0xc0006e2000, 0xc0002020f0, 0xc0003a6834, 0x4, 0xc0003a6840, 0x10, 0x1)
lio-prod_lioctad.1.y2owyavvvr3y@lioctad    | 	github.com/dechristopher/lioctad/www/ws/handlers/handle_move.go:125 +0x21d
lio-prod_lioctad.1.y2owyavvvr3y@lioctad    | created by github.com/dechristopher/lioctad/www/ws/handlers.HandleMove
lio-prod_lioctad.1.y2owyavvvr3y@lioctad    | 	github.com/dechristopher/lioctad/www/ws/handlers/handle_move.go:65 +0x479
```

**Comment by dechristopher** [comment]
Fixed in 1ca88cb
